language: node_js
node_js:
  - 0.8
install:
  - "npm install grunt-cli -g"
  - npm install
env:
  global:
    - SAUCE_USERNAME="sourishkrout"

addons:
  - jwt:
    - secure: au5TMV32hysZdgyeHs7c2Te/xz6SYSVybQPvWInoJtnlxdWkphaVmmULWEIPmW10iQcH5AEw6L9hZYLgCowSRXlZsYOKcKoNBtNXkh4eGMFbp2V16K++1xAtnk9vJ3Um6gRdG4BiGdmDvFI+Vvw85UttopJbPpS/S7FOLp1dehE=
