language: node_js
node_js:
  - 0.10
install:
  - "npm install grunt-cli -g"
  - npm install
env:
  global:
    - SAUCE_USERNAME="sourishkrout"

addons:
  jwt:
     saucelabs:
        secure: "hi3PEkkRCUHejkPKqIM7c+q8ZwTq1wB/e6CS2w0IapFv0Kik+WzLCv+KME/3r+wi5cNw5M62ST/U9dNxJEp9D1QhRaAYNFNgzSIEJtU0wvO3zQxoOVAK8q6p9seO6mODYq62M90M+vpER98A4wbGITPna7CPPPdHnFzCE4RVJMM="
