language: node_js
node_js:
  - 0.8
install:
  - "npm install grunt-cli -g"
  - npm install
env:
  global:
    - SAUCE_USERNAME="sourishkrout"

addons:
  - jwt:
    - secure: "fjhlH/cSJvksNvNDGjjDkHcO5BnIbMyYkC0cGAiPXKjcHPNcdGQc6xnKSygMbg08lT+9L4rFaWb7Mx9czspDixySkyXWZ+BD3/cooZ2Hm5BRoRYtrmWFfk16mxz9k2vluGH3R6vyMrjKaf+dCRvc6QiUO5kKiX4mccS6QB8JFzU="
