language: node_js
node_js:
  - 0.10
install:
  - "npm install grunt-cli -g"
  - npm install
env:
  global:
    - SAUCE_USERNAME="sourishkrout"

addons:
  jwt:
     saucelabs:
        secure: "eDQEcNFA0nQzTUj1HmnedM8+vWtaxLehmEgDzf/EEI/Bk6tYcnJMqpA0VMklUDsdmkpxpMRgspdrv1+T4LdYFGMJUOJ+4A7DjkEiTvpKammhgRRYja3VjSpBjx8svxvxwLOHY6l81xRglsdjyWrCx87gUNBr5jFZ5Pd0SJM3LqI="
